[package]
name = "azfeed"
version = "0.1.0"
authors = ["Mordecai Malignatus <mordecai@malignat.su>"]
edition = "2018"

[dependencies]
rss = "1.9.0"
web-view = "0.6.2"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.4.2"
quick-xml = "0.18.1"
