* Azfeed

A very simple solution to keep up to date with your RSS feeds, with none of the
frills or features of more fully featured offerings.

** Features
- File-based: A single file controls everything, from feeds subscribed to,
  to what counts as "unread".
- Simple: The entire thing exists to keep up to date with RSS feeds. For more
  sophisticated collections, tagging, etc, I would suggest Pinboard instead.

** Anti-Features
- Tagging.
- Collections.
- Long-standing daemons that do the feed-fetching. Yes, this means that startup
  will be slow, as all feeds will be fetched on startup.

* Getting Started

The core idea is CLI based, but presentation relies on a (crossplatform) web
renderer.

** Importing OPML
I wrote a simple way of taking an OPML (which is a standard format you can get
from things like Feedly, etc) and importing it to be your =feeds.toml= instead.

The CLI interface for that isn't yet written but it'll look something like
=azfeed import-opml /path/to/opml= which will simply write
